config/routes.rb
Edgar::Application.routes.draw do
  get "backdoor/play1"
  get "backdoor/play2"
  get "backdoor/play3"
  get "tags/index"

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/  do
    authenticated :user do
      root :to => 'home#index'
      get "search/index"
    end

    devise_scope :user do
      root :to => "showcase#index", :as => "locale_root", constraints: {subdomain: 'www'}
      match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
      match '', to: 'sessions#new', constraints: {subdomain: /.+/}
      get "features", to: "showcase#features"
      get "about", to: "showcase#about"
    end

    devise_for :users, :controllers => { :registrations => "registrations", :confirmations => "confirmations", :sessions => "sessions"}
    match 'users/bulk_invite/:quantity' => 'users#bulk_invite', :via => :get, :as => :bulk_invite
    resources :users do
      get 'invite', :on => :member
    end

    get "welcome", to: "welcome#index"
    get "home", to: "home#index"
    get "dashboard", to: "dashboard#index"

    resources :structures do
      put 'people/:id/set_main_person', action: :set_main_person, as: :set_main_person
      resources :people
    end
    resources :people_structures, only: [:create]
    resources :festivals
    resources :show_buyers
    resources :venues do
      resources :people
      resources :tasks do
        put 'complete', :on => :member
        put 'uncomplete', :on => :member
      end
    end
    resources :people do
      resources :tasks do
        put 'complete', :on => :member
        put 'uncomplete', :on => :member
      end
    end
    resources :tasks do
      put 'complete', :on => :member
      put 'uncomplete', :on => :member
    end
    resources :contacts do
      get 'autocomplete', on: :collection
      put 'bulk', on: :collection
      resources :tasks do
        put 'complete', :on => :member
        put 'uncomplete', :on => :member
      end

      get 'only/:filter', action: :only, on: :collection, as: :only
      get 'add_to_favorites', on: :member
      get 'remove_to_favorites', on: :member
      get 'show_map', on: :collection
    end

    resource :account do
      put 'import_samples', action: :import_samples, as: :import_samples
      delete 'destroy_test_contacts', action: :destroy_test_contacts

      resources :abilitations
    end

    resources :reportings

    resources :campaigns
    resources :opportunities

    resources :projects

    resources :styles, only: [:index]
    resources :networks, only: [:index]
    resources :customs, only: [:index]

    resources :jobs, only: [:show]

    resources :contacts_imports, only: [:new, :create, :update]
    get 'contacts_imports/new_with_details', to: 'contacts_imports#new_with_details', as: :new_with_details_contacts_import

    resources :contacts_exports, only: [:new]

    resources :announcements, only: [:index]
    resources :coupons, only: [:index, :new, :create, :update]
    resources :addresses, only: [:update]
    resource :subscription, only: [:new, :edit, :create, :update]
  end

  require "sidekiq/web"
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end if Rails.env.production?
  mount Sidekiq::Web, at: "/sidekiq"

  root to: redirect("/#{I18n.default_locale}")
end

app/controllers/showcase_controller.rb
class ShowcaseController < Devise::SessionsController
  layout "multipage"

  def index
  end

  def features
  end

  def about
  end
end

app/views/showcase/_cta-enroll.html.haml
%section.cta.cta-black#cta-enroll
  - user = User.new
  = form_for(user, url: new_user_registration_path, method: :get) do |f|
    .container
      %h3 Combien ça coûte ?

      :markdown

        C'est aujourd'hui gratuit !

        L'utilisation de Merci Edgar sera bientôt reservée aux adhérents de l'association (une fois la fonctionnalité d'export opérationnelle).

        Réponses aux questions fréquemment posées sur l'[association Merci Edgar](http://blog.merciedgar.com/post/108265370123/reponses-aux-questions-frequemment-posees).

        Pour info, le montant de l'adhésion est symbolique : elle est fixée à 20€ par an pour les particuliers (et permet de couvrir notamment les frais d'hébergement)

      .row-fluid
        .span5.offset1
          = f.text_field(:email, placeholder: "Votre email")
        .span5
          = f.button "Je m'inscris !", class: "btn btn-large btn-danger btn-block"

app/views/showcase/_footer.html.haml
= render 'showcase/cta-enroll'

%footer#contact-section.footer
  .container
    .row-fluid
      .span8
        = link_to locale_root_path do
          .logo-ed.logo-footer.edi-ed-logo-typo
        %address
          %i.fa-icon-map-marker
          Au bourg, 47120 Monteton, France
      .span4
        %ul.socials
          %li
            %a{:href => "https://www.facebook.com/pages/Merci-Edgar/164510577033726", :title => "Facebook Merci Edgar", :target => "blank"}
              %i.ico.edi-facebook
          %li
            %a{:href => "https://twitter.com/MerciEdgar", :title => "Twitter Merci Edgar", :target => "blank"}
              %i.ico.edi-twitter
          %li
            %a{:href => "http://vimeo.com/channels/entretiensdedgar", :title => "Vimeo Channel Entretiens d'Edgar", :target => "blank"}
              %i.ico.edi-vimeo

app/views/showcase/_head.html.haml
%meta{:content => content_for?(:description) ? yield(:description) : "Edgar", :name => "description"}
= csrf_meta_tags
%meta{:charset => "utf-8"}/
%title Merci Edgar | L'assistant virtuel des artistes
%meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
%meta{:content => "Merci Edgar, #{t("baseline")}", :name => "description"}/
%meta{:content => "Merci Edgar", :name => "author"}/

%meta{:content => "Merci Edgar, #{t("baseline")}", :property => "og:title"}/
%meta{:content => "#{t("home.slogan.are_you_artist")} #{t("home.slogan.time")} Merci Edgar #{t("home.slogan.edgar_for_you")}", :property => "og:description"}/

= yield :facebook_og


= stylesheet_link_tag "multipage"

/[if lt IE 9]
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>

= favicon_link_tag 'favicon.ico'

/[if gte IE 9] <style type="text/css"> \.gradient { filter: none;} </style>

app/views/showcase/_header.html.haml
%header
  .nav-top

    #top-nav.navbar.navbar-fixed-top
      .navbar-inner
        .container
          %button.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse", :type => "button"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          .logo
            = link_to locale_root_path do
              .logo-ed.logo-header.edi-ed-logo-horiz

          #main-nav
            %nav.nav-collapse.collapse.pull-right
              %ul#nav.nav
                = showcase_menu_link("Fonctionnalités et Tarifs", features_path, "features")
                = showcase_menu_link("À propos", about_path, "about")
                %li= link_to "Blog", "http://blog.merciedgar.com", target: "_blank"
                %li
                  %a.btn.btn-enroll{href: "#cta-enroll"}
                    S'inscrire

              #login-tab
                - if user_signed_in?
                  - if current_user.has_role? :admin
                    = link_to "Administration", users_path

                  = link_to t("simple_form.labels.defaults.signout"), destroy_user_session_path, :method => :delete, :class => "login-btn"
                - else
                  .login-btn.login-toggle
                    =t("simple_form.labels.defaults.signin")

              #login-form.invisible
                .form-signin
                  = simple_form_for(resource, :as => resource_name, :url => session_path(resource_name), :html => {:class => 'form-vertical' }) do |f|
                    = f.input_field :email, :autofocus => true, :class => "medium", placeholder:"#{t("simple_form.labels.defaults.email")}"
                    = f.input_field :password, :class => "small", :placeholder => "#{t("simple_form.labels.defaults.password")}"

                    - if devise_mapping.recoverable? && controller_name != 'passwords'
                      = link_to "?", new_password_path(resource_name), :class => "login-btn forgot-btn", :rel => "tooltip", "data-placement" => "bottom", :title => "Mot de passe oublié ?"
                    = f.button :submit, t("simple_form.labels.defaults.signin"), :class => 'login-btn login-submit'
                .close-btn.login-btn.login-toggle x

  = yield(:hero)

app/views/showcase/_javascripts.html.haml
/ Placed at the end of the document so the pages load faster
= javascript_include_tag "multipage/application"
:javascript
  jQuery(function(){
  	jQuery('#tweets').tweetable({
  		username: 'wrapbootstrap', 
  		time: true,
  		rotate: true,
  		speed: 4000, 
  		limit: 2,
  		replies: false,
  		position: 'append',
  		failed: "Sorry, twitter is currently unavailable for this user.",
  		html5: true,
  		onComplete:function(jQueryul){
  			jQuery('time').timeago();
  		}
  	});
  });
  
/ Google Analytics
:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-35382203-3', 'merciedgar.com');
  ga('send', 'pageview');
  

app/views/showcase/_submenu.html.haml
.container.submenu
  -#
    #langswitch.noselect
    
      = link_to "FR", "/fr", :class => params[:locale].eql?("fr") ? 'active' : ''
      |
      = link_to "EN", "/en", :class => params[:locale].eql?("en") ? 'active' : ''
    
    -#
      %a.btn{"data-content" => "Vivamus sagittis lacus vel augue laoreet rutrum faucibus.", "data-original-title" => "FR", "data-placement" => "bottom", "data-toggle" => "popover", href: "#", title: ""} FR
    
  
    
  -# SOCIALS __________________________________________________________
  #socialfixed
    %ul.socials
      %li
        %a{:href => "https://www.facebook.com/pages/Merci-Edgar/164510577033726", :title => "Facebook Merci Edgar", :target => "blank"}
          %i.ico.edi-facebook
          
      %li
        %a{:href => "https://twitter.com/MerciEdgar", :title => "Twitter Merci Edgar", :target => "blank"}
          %i.ico.edi-twitter
          
      %li
        %a{:href => "http://vimeo.com/channels/entretiensdedgar", :title => "Vimeo Channel Entretiens d'Edgar", :target => "blank"}
          %i.ico.edi-vimeo
/ END SOCIALS

app/views/showcase/features.html.haml
- content_for :hero do
  / HEADER MAIN
.hero-unit.notfullimg#hero-features
  .container
    = render 'showcase/submenu'
    .thehero
      %h4 Voici vos nouveaux meilleurs amis :
      = image_tag("multipage/showcase-banner-feat.png")



- content_for :facebook_og do
  = tag('meta', content: "#{request.base_url}/#{image_path('multipage/screenys/scr_560_teamwork.jpg')}", property: "og:image")
  = tag('meta', content: "#{request.base_url}/#{image_path('multipage/screenys/scr_560_map.jpg')}", property: "og:image")
  = tag('meta', content: "#{request.base_url}/#{image_path('multipage/screenys/scr_560_filters.jpg')}", property: "og:image")
  = tag('meta', content: "#{request.base_url}/#{image_path('multipage/screenys/scr_560_reporting.jpg')}", property: "og:image")


%section.bkg-white.feat-section
  %space
  .container
    .row-fluid
      .span5
        %h3 Gérer votre base contacts
        %p
          Merci Edgar permet aux artistes et aux tourneurs de gérer leurs contacts professionnels (lieux, festivals, autres organisateurs de spectacles, mais aussi tout type de structure comme les médias, les institutionnels, les imprimeurs, ...) à l'aide d'une interface simple et intuitive.
        %p.notes
          L’import de vos fichiers Excel bientot disponible

      .span7
        .img-box
          = image_tag("multipage/screenys/scr_560_list.jpg")

%section.bkg-white.feat-section
  .container
    .row-fluid
      .span7
        .img-box
          /.sticker.sticker-small Prochainement
          = image_tag("multipage/screenys/scr_560_reporting.jpg")
      .span5
        %h3 Travaillez vos contacts !
        %p
          Assignez-vous des tâches à propos de tel contact, rédigez des comptes-rendus pour suivre vos différentes intéractions avec vos contacts. En un mot, faites d'Edgar votre assistant virtuel qui saura tout de vos contacts pro !

%section.bkg-white.feat-section
  .container
    .row-fluid
      .span5
        %h3 Segmentez et recherchez !
        %p
          Une fois vos contacts correctement qualifiés, profitez de notre puissant moteur de recherche pour segmenter votre base de données à l'aide de recherche multi-critères (par esthétique, proximité géographique, jauge,…) Envie de trouver dans votre base tous les lieux qui programment de la chanson, avec une jauge de moins de 100 personnes, dans un rayon de 100 km de Nantes ? Demandez à Edgar, en un clic, il vous apportera la réponse !
      .span7
        .img-box
          = image_tag("multipage/screenys/scr_560_filters.jpg")
  %space



%section.bkg-white.feat-section
  .container
    .row-fluid
      .span7
        .img-box
          = image_tag("multipage/screenys/scr_560_map.jpg")
      .span5
        %h3 Géolocalisez !
        %p
          Une fois l'adresse de votre contact pro renseigné, Edgar saura le situer sur une carte. La géocalisation couplée avec notre puissant moteur de recherche vous permettra de trouver vos différents contacts (lieux, festivals, autres organisateurs de spectacles,…) à une certaine distance d'un lieu. Pratique pour organiser une tournée !
  %space



%section.bkg-white.feat-section
  .container
    .row-fluid
      .span5
        %h3 Travaillez en équipe !
        %p
          Edgar vous permet un accès multi-utilisateurs à votre base. Vous saurez qui a rédigé le dernier compte-rendu sur tel contact, vous pourrez assigner une tâche à un de vos collèques. En un mot, vous pourrez travailler en équipe grâce à Edgar !
      .span7
        .img-box
          = image_tag("multipage/screenys/scr_560_teamwork.jpg")
  %space

%section.cta.cta-brown
  .container
    .section-title
      %h2 Les premiers pas sur Merci Edgar en vidéo :
    <iframe src="//player.vimeo.com/video/86027838?byline=0&amp;portrait=0&amp;color=fff" width="560" height="315" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>

%section#soon-section
  .container
    .section-title
      %h2 Prochainement
      %p La version actuelle de pré-lancement de Merci Edgar ne contient que le module "Gestion de contacts". Nous sommes en train de développer de nouveaux modules (administration, communication).

    .row-fluid.label-blocks
      .span4
        .label.label-large
          %i.ico.edi-dates
        %h4 Module administration
        %p gestion et suivi d'une date vendue

      .span4
        .label.label-large
          %i.ico.edi-megaphone
        %h4 Module communication
        %p il permettra de coupler sa base de données Merci Edgar avec des outils d'envoi de mail en masse notamment

      .span4
        .label.label-large
          %i.ico.edi-mobile
        %h4 Edgar Mobile
        %p Une version mobile est en cours de développement.

%section
  .container
    %h2.section-title= t("home.promise.why")
    .row-fluid
      .span6
        %p
          = t("home.promise.alone")
          %br/
          = t("home.promise.more_time_for")
          %br/
          = t("home.promise.goal")

      .span6
        .row.paragraph-middle
          %ul.engagements
            %li
              %strong= t("home.commitments.free")
              %br/
              = t("home.commitments.free_details")
            %li
              %strong= t("home.commitments.simple")
              %br/
              = t("home.commitments.simple_details")
            %li
              %strong= t("home.commitments.no_installation")
              %br/
              = t("home.commitments.no_installation_details")
            %li
              %strong= t("home.commitments.byfor")
              %br/
              = t("home.commitments.byfor_details")
            %li
              %strong= t("home.commitments.evolutive")
              %br/
              = t("home.commitments.evolutive_details")

app/views/showcase/index.html.haml
- content_for :facebook_og do
  = tag('meta', content: "#{request.base_url}/#{image_path('multipage/edgar-head.png')}", property: "og:image")
  = tag('meta', content: "#{request.base_url}/#{image_path('multipage/vitrinne-banner-launch2.jpg')}", property: "og:image")

- content_for :hero do
  .hero-unit#hero-launch.gradient
    .container
      = render 'showcase/submenu'
    .row-fluid.hero-launch
      = image_tag("multipage/vitrinne-banner-launch2.png")

%section#features-section
  .container
    .row-fluid.label-blocks
      .span4
        .label.label-large.label-info
          = image_tag("multipage/pic-photo-2.png")
        %h4= t("home.features.track_1")
        %p= t("home.features.track_what_1")
      .span4
        .label.label-large.label-info
          = image_tag("multipage/pic-photo-4.png")
        %h4= t("home.features.schedule")
        %p= t("home.features.schedule_what")
      .span4
        .label.label-large.label-info
          = image_tag("multipage/pic-photo-3.png")
        %h4= t("home.features.communicate")
        %p= t("home.features.communicate_what").html_safe
%section.cta.cta-invi
  .container
    %h3
      = link_to features_path do
        %i.ico.edi-info2
          Découvrir les fonctionnalités de Merci Edgar
%space