config/routes.rb
Edgar::Application.routes.draw do
  get "backdoor/play1"
  get "backdoor/play2"
  get "backdoor/play3"
  get "tags/index"

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/  do
    authenticated :user do
      root :to => 'home#index'
      get "search/index"
    end

    devise_scope :user do
      root :to => "showcase#index", :as => "locale_root", constraints: {subdomain: 'www'}
      match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
      match '', to: 'sessions#new', constraints: {subdomain: /.+/}
      get "features", to: "showcase#features"
      get "about", to: "showcase#about"
    end

    devise_for :users, :controllers => { :registrations => "registrations", :confirmations => "confirmations", :sessions => "sessions"}
    match 'users/bulk_invite/:quantity' => 'users#bulk_invite', :via => :get, :as => :bulk_invite
    resources :users do
      get 'invite', :on => :member
    end

    get "welcome", to: "welcome#index"
    get "home", to: "home#index"
    get "dashboard", to: "dashboard#index"

    resources :structures do
      put 'people/:id/set_main_person', action: :set_main_person, as: :set_main_person
      resources :people
    end
    resources :people_structures, only: [:create]
    resources :festivals
    resources :show_buyers
    resources :venues do
      resources :people
      resources :tasks do
        put 'complete', :on => :member
        put 'uncomplete', :on => :member
      end
    end
    resources :people do
      resources :tasks do
        put 'complete', :on => :member
        put 'uncomplete', :on => :member
      end
    end
    resources :tasks do
      put 'complete', :on => :member
      put 'uncomplete', :on => :member
    end
    resources :contacts do
      get 'autocomplete', on: :collection
      put 'bulk', on: :collection
      resources :tasks do
        put 'complete', :on => :member
        put 'uncomplete', :on => :member
      end

      get 'only/:filter', action: :only, on: :collection, as: :only
      get 'add_to_favorites', on: :member
      get 'remove_to_favorites', on: :member
      get 'show_map', on: :collection
    end

    resource :account do
      put 'import_samples', action: :import_samples, as: :import_samples
      delete 'destroy_test_contacts', action: :destroy_test_contacts

      resources :abilitations
    end

    resources :reportings

    resources :campaigns
    resources :opportunities

    resources :projects

    resources :styles, only: [:index]
    resources :networks, only: [:index]
    resources :customs, only: [:index]

    resources :jobs, only: [:show]

    resources :contacts_imports, only: [:new, :create, :update]
    get 'contacts_imports/new_with_details', to: 'contacts_imports#new_with_details', as: :new_with_details_contacts_import

    resources :contacts_exports, only: [:new]

    resources :announcements, only: [:index]
    resources :coupons, only: [:index, :new, :create, :update]
    resources :addresses, only: [:update]
    resource :subscription, only: [:new, :edit, :create, :update]
  end

  require "sidekiq/web"
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end if Rails.env.production?
  mount Sidekiq::Web, at: "/sidekiq"

  root to: redirect("/#{I18n.default_locale}")
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :account
  belongs_to :user
  belongs_to :asset, polymorphic: true
  belongs_to :assignee, class_name: "User", foreign_key: :assigned_to
  belongs_to :completor, class_name: "User", foreign_key: :completed_by
  belongs_to :project

  attr_accessible :bucket, :assigned_to, :user_id, :name, :asset_id, :asset_type, :calendar, :specific_time, :project_id
  attr_accessor :calendar

  validates :user, :name, presence: true

  default_scope { where(:account_id => Account.current_id).order('tasks.due_at ASC') }
  scope :tracked_by, lambda { |user_id| where('user_id = ? OR assigned_to = ?', user_id, user_id) }
  scope :by_project, lambda { |project_id| where(project_id: project_id) }

  scope :pending,       where('completed_at IS NULL').order('tasks.due_at, tasks.id')
  scope :assigned,      where('completed_at IS NULL AND assigned_to IS NOT NULL').order('tasks.due_at, tasks.id')
  scope :completed,     where('completed_at IS NOT NULL').order('tasks.completed_at DESC')

  scope :overdue,       lambda { where('due_at IS NOT NULL AND due_at < ?', Time.zone.now.midnight.utc).order('tasks.due_at ASC') }
  scope :due_today,     lambda { where('due_at >= ? AND due_at < ?', Time.zone.now.midnight.utc, Time.zone.now.midnight.tomorrow.utc).order('tasks.due_at ASC') }
  scope :due_tomorrow,  lambda { where('due_at >= ? AND due_at < ?', Time.zone.now.midnight.tomorrow.utc, Time.zone.now.midnight.tomorrow.utc + 1.day).order('tasks.due_at ASC') }
  scope :due_this_week, lambda { where('due_at >= ? AND due_at < ?', Time.zone.now.midnight.tomorrow.utc + 1.day, Time.zone.now.next_week.utc).order('tasks.due_at ASC') }
  scope :due_next_week, lambda { where('due_at >= ? AND due_at < ?', Time.zone.now.next_week.utc, Time.zone.now.next_week.end_of_week.utc + 1.day).order('tasks.due_at ASC') }
  scope :due_this_month, lambda { where('due_at >= ? AND due_at < ?', Time.zone.now.next_week.end_of_week.utc + 1.day, Time.zone.now.end_of_month.utc + 1.day).order('tasks.due_at ASC') }
  scope :due_later,     lambda { where("(due_at IS NULL AND bucket = 'due_later') OR due_at >= ?", Time.zone.now.next_week.end_of_week.utc + 1.day).order('tasks.due_at ASC') }

  def asset_type=(sType)
    super(sType.to_s.classify.constantize.base_class.to_s)
  end

  def complete(user)
    self.completor = user
    self.completed_at = Time.zone.now
  end

  def uncomplete
    self.completed_at = nil
    self.completed_by = nil
  end

  def assign_to(user)
    self.assignee = user
    save
  end

  def assignee_name
    self.assignee.name if self.assignee
  end

  def bucket
    return "due_today" if self.due_at.blank?
    return "specific" if self.specific_time
    case
    when self.due_at < Time.zone.now
      "overdue"
    when self.due_at >= Time.zone.now.midnight && self.due_at < Time.zone.now.midnight.tomorrow
      "due_today"
    when self.due_at >= Time.zone.now.midnight.tomorrow && self.due_at < Time.zone.now.midnight.tomorrow + 1.day
      "due_tomorrow"
    when self.due_at >= (Time.zone.now.midnight.tomorrow + 1.day) && self.due_at < Time.zone.now.next_week
      "due_this_week"
    when self.due_at >= Time.zone.now.next_week && self.due_at < (Time.zone.now.next_week.end_of_week + 1.day)
      "due_next_week"
    else
      "due_later"
    end
  end

  def bucket=(s)
    self.specific_time = false
    self.due_at = case s
    when "overdue"
      Time.zone.now.end_of_day.yesterday
    when "due_today"
      Time.zone.now.end_of_day
    when "due_tomorrow"
      Time.zone.now.end_of_day.tomorrow
    when "due_this_week"
      Time.zone.now.end_of_day.end_of_week
    when "due_next_week"
      Time.zone.now.end_of_day.next_week.end_of_week
    when "due_this_month"
      Time.zone.now.end_of_day.end_of_month
    when "due_later"
      Time.zone.now.midnight + 100.years
    else # due_later or due_asap
      nil
    end
  end

  def to_ics
    event = Icalendar::Event.new
    event.dtstart = self.due_at.strftime("%Y%m%dT%H%M%S")
    event.summary = self.name
    event.last_modified = self.updated_at.strftime("%Y%m%dT%H%M%S")
    event
  end

  def friendly_date
    date = self.completed_at.present? ? completed_at : self.due_at
    if date
      case
      when date < Time.zone.now && completed_at.present?
        ["green", I18n.localize(date.in_time_zone, format: :short)]

      when date < Time.zone.now && !completed_at.present?
        ["black", "#{I18n.t(:overdue)} // #{I18n.localize(date.in_time_zone, format: :short)}"]

      when date >= Time.zone.now.midnight && date < Time.zone.now.midnight.tomorrow
        ["red", self.specific_time? ? I18n.localize(date.in_time_zone, format: :friendly_day, day:I18n.t(:due_today)) : I18n.t(:due_today)]

      when date >= Time.zone.now.midnight.tomorrow && date < Time.zone.now.midnight.tomorrow + 1.day
        ["blue", self.specific_time? ? I18n.localize(date.in_time_zone, format: :friendly_day, day:I18n.t(:due_tomorrow)) : I18n.t(:due_tomorrow)]

      when date >= (Time.zone.now.midnight.tomorrow + 1.day) && date < Time.zone.now.next_week
        ["green", self.specific_time? ? I18n.localize(date.in_time_zone, format: :friendly) : I18n.t(:due_this_week)]

      when date >= Time.zone.now.next_week && self.due_at < (Time.zone.now.next_week.end_of_week + 1.day)
        ["gray", self.specific_time? ? I18n.localize(date.in_time_zone, format: :friendly) : I18n.t(:due_next_week)]

      when date >= Time.zone.now.next_week.end_of_week + 1.day && date < Time.zone.now.end_of_month + 1.day
        ["gray", self.specific_time? ? I18n.localize(date.in_time_zone, format: :short) : I18n.t(:due_this_month)]
      else
        ["gray", self.specific_time? ? I18n.localize(date.in_time_zone, format: :short) : I18n.t(:due_later)]
      end
    end
  end

end

app/controllers/tasks_controller.rb
# encoding: utf-8
class TasksController < ApplicationController

  def new
    @asset = Contact.find(params[:contact_id]) if params[:contact_id]
    @task = Task.new
    @task.project = Project.first
    @users = Account.find(Account.current_id).users
  end

  def edit
    @task = Task.find(params[:id])
    @asset = Contact.find(params[:contact_id]) if params[:contact_id]
    @users = Account.find(Account.current_id).users
  end

  def update
    @task = Task.find(params[:id])
    @asset = @task.asset
    if @task.update_attributes(params[:task])
      if @asset
        @pending_tasks = @task.asset.tasks.pending
        @completed_tasks = @task.asset.tasks.completed
      else
        @redirect = true
      end
    else
      render :edit
    end
  end

  def complete
    @task = Task.find(params[:id])
    @task.complete(current_user)
    if @task.save
      # head :no_content
      render "complete"
    end
  end

  def uncomplete
    @task = Task.find(params[:id])
    @task.uncomplete
    if @task.save
      render "uncomplete"
    end
  end

  def create
    @task = Task.new(params[:task])
    @asset = @task.asset
    if @task.save
      if @asset
        @pending_tasks = @task.asset.tasks.pending
        @completed_tasks = @task.asset.tasks.completed
      else
        @redirect = true
      end
      respond_to do |format|
        format.html { redirect_to tasks_path }
        format.js
      end
    else
      respond_to do |format|
        format.js { render json: "Erreur durant la création de la tache. (#{@task.errors.full_messages})", status: :error }
      end
    end
  end

  def index
    @tasks = Task.order("due_at ASC")
    @tasks = @tasks.tracked_by(params[:user_id]) if params[:user_id]
    @tasks = @tasks.by_project(params[:project_id]) if params[:project_id]
    @pending_tasks = @tasks.pending
    @completed_tasks = @tasks.completed

    if params[:user_id] && User.exists?(params[:user_id])
      @selected_user =  User.find(params[:user_id])
    else
      @selected_user = "Tous les utilisateurs"
    end

    respond_to do |format|
      format.html
      format.ics do
        calendar = Icalendar::Calendar.new
        calendar.prodid = "MerciEdgar-Calendar"
        @tasks.each do |t|
          calendar.add_event(t.to_ics)
        end
        render :text => calendar.to_ical
      end
    end
  end
end

app/views/tasks/_ajax_errors.html.haml
- @task.errors.full_messages.each do |m|
  .alert.alert-error= m
    

app/views/tasks/_ajax_form.html.haml
#myModalContent
  .modal-header
    %a.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
    %h3#myModalLabel Créer une tâche
    <br>
    = "relative à #{@asset}" if @asset

  = simple_form_for([@task],remote:true) do |f|
    .modal-body
      .errors    
      .form-inputs
        = f.hidden_field :user_id, :value => current_user.id
        = f.hidden_field :asset_id, :value => @asset.id if @asset
        = f.hidden_field :asset_type, :value => @asset.class.name if @asset
        .row-fluid
          = f.input :name, label: false, autofocus: true, :input_html => { :class => "big-input span12" }
        .row-fluid
          = f.input :bucket, :collection => [:due_today, :due_tomorrow, :due_this_week, :due_next_week, :due_this_month, :overdue, :specific], label: "Pour quand ?", :input_html => { :class => "" }
      
          = f.input :calendar, :input_html => {"data-date-format" => "dd/mm/yyyy hh:ii", "data-date-language" => "fr", "data-date-autoclose" => true, "data-date-today-btn" => "linked", "data-date-today-highlight" => true, :class => "datepicker "}, label: false
      
        = f.input :assigned_to, collection: @users, label_method: :display_name, value_method: :id, selected: current_user.id
      
        = f.input :project_id, collection: Project.all, label_method: :name, value_method: :id, prompt: "Aucun projet", label: t("simple_form.labels.project.name")
        / if zero projects :
        .message
        - unless Project.any?
          %i.entypo.edi-warning
          Vous n’avez encore créé de projet artistique !
          %br
          = link_to "Cliquez ici pour créer un projet", projects_path
    .modal-footer
      /.btn.btn-secondary
      = f.button :submit, class:"btn-primary btn-large pull-right"
      %button.btn.btn-link{"aria-hidden" => "true", "data-dismiss" => "modal"} Annuler

app/views/tasks/_empty_tasks.html.haml
#empty_tasks
  %section
    %h3.message
      Aucune tâche relative à
      %span.bold= asset

  %section
    .row-fluid.label-blocks
      .span4
        = link_to new_contact_task_path(asset), :class => "label label-large", remote:true do
          /= link_to new_venue_path, :class => "label label-large" do
          %i.edi-check
          %h4 Créer une tâche
          %p= "pour #{asset}"

app/views/tasks/_form.js.erb
$('#myModalContent').replaceWith('<%= j render("ajax_form") %>');
$('.datepicker').datetimepicker();

$('.task_calendar').hide();

$('#task_bucket').change(function() {
  $('.datepicker').val("");
  if ( $(this).val() == "specific" ) {
    $('.task_calendar').css('display', 'inline-block');
    $('.datepicker').focus();
  } else {
    $('.task_calendar').hide();
  }
});

$('.datepicker').change(function() {
  $('#task_bucket').val("specific");
});

$('#myModal').modal('toggle')

app/views/tasks/_group_old.html.haml
- if (the_tasks = tasks.send(due)).any?
  %ul.list-medium
    - the_tasks.send(due).each do |t|
      %li
        .rightrow.small
          = show_badge(color, t.specific_time? ? t.friendly_date : t(due))
          .actions
            -#%a.shybtn{:href => "#"}
            - if asset.present?
              = link_to send("edit_#{asset.class.name.downcase}_task_path",asset,t), :class => "shybtn" do
                %i.entypo.edi-pencil
            - else
              = link_to edit_task_path(t), :class => "shybtn" do
                %i.entypo.edi-pencil

        .rightrow
          .s1of2
            %a{:href => "#"}
              .pic.pic-mini= image_tag "squared/pro2.jpg"
              ProjetXqsd
          .s1of2
            %a{:href => "#"}
              .pic.pic-mini= image_tag t.assignee.avatar
              = t.assignee.nickname

        .mainrow
          %input{:type => "checkbox"}
          - if asset.present?
            = link_to t.name, send("edit_#{asset.class.name.downcase}_task_path",asset,t)
          - else
            = link_to t.name, edit_task_path(t)

app/views/tasks/_tasks.html.haml
- if pending_tasks.any?
  #pending_tasks_wrapper
    .title-infos
      /dont
      - if pending_tasks.overdue.any?
        .badge.badge-small.badge-black= pending_tasks.overdue.size
        tâches en retard,
      - if pending_tasks.due_today.any?
        .badge.badge-small.badge-red= pending_tasks.due_today.size
        tâches pour aujourd’hui  

    = render :partial => "tasks/pending", :locals => {:tasks => pending_tasks, :asset => asset}

    
    
#completed_tasks_wrapper
  .title-infos
    .badge.badge-small.badge-black= @completed_tasks.size
    = link_to "#", data: {toggle: "collapse", target: "#completed_tasks"} do
      
      Tâches effectuées
  = render :partial => "tasks/completed_tasks", :locals => {:tasks => completed_tasks}

app/views/tasks/complete.js.erb
li_task = $('#task_<%= @task.id %>');
li_task.wrap("<strike></strike>");
setTimeout("complete(li_task)",4000);

function complete(li_task) {
	checkbox = li_task.find("input")
	if (checkbox.is(':checked')) {
		li_task.fadeOut(500, function() { clean_and_refresh_completed_tasks(li_task)  })
    console.log("task complete")
	}
}

function clean_and_refresh_completed_tasks(li_task) {
	li_task.remove();
  
  var $counter = $("#pending_tasks_wrapper .title-infos .badge");
  $counter.text( Number($counter.text())-1 );
  
  var $counter2 = $("#completed_tasks_wrapper .title-infos .badge");
  $counter2.text( Number($counter2.text())+1 );
  
	completed_tasks = $('#completed_tasks');
	if (completed_tasks.length > 0) {
		<% if @task.asset %>		
			completed_tasks.replaceWith("<%= j render(partial:'completed_tasks', locals: {tasks: @task.asset.tasks.completed}) %>")
		<% else %>
			completed_tasks.replaceWith("<%= j render(partial:'completed_tasks', locals: {tasks: Task.order("due_at ASC").completed}) %>")
		<% end %>
		
	}
	
}

app/views/tasks/edit.html.haml
%h1 Editer la tâche

= render 'form'

app/views/tasks/edit.js.erb
$('#myModalContent').replaceWith('<%= j render("ajax_form") %>');
$('.datepicker').datetimepicker();


if ( $("#task_bucket").val() == "specific" ) {
  $('.task_calendar').show();
} else {
   $('.task_calendar').hide();
}




$('#task_bucket').change(function() {
  $('.datepicker').val("");
  
  //alert( $('#task_bucket').val() )
  
  if ( $(this).val() == "specific" ) {
    //$('.task_calendar').show();
    $('.task_calendar').css('display', 'inline-block');
    //$(this).next().focus();
    $('.datepicker').focus();
    
    } else {
      $('.task_calendar').hide();
    }
    
    
});



$('.datepicker').change(function() {
  $('#task_bucket').val("specific");
});


$('#myModal').modal('toggle')

app/views/tasks/errors.js.erb
$('.errors').replaceWith('<%= escape_javascript render("ajax_errors") %>');

app/views/tasks/index.html.haml
%header.page-title
  = t(params[:controller]).titleize
  = @filtered_by if @filtered_by.present?

  .subpage-nav
.sorters
  .dropdown
    %button.btn.btn-tertiary.dropdown-toggle{"data-toggle" => "dropdown", type: "button"}
      = @selected_user
      %i.entypo.caret-ed
    %ul.dropdown-menu{"aria-labelledby" => "dropdownMenu1", role: "menu"}
      - if params[:user_id]
        %li{role: "menuitem"}
          = link_to "Tous les utilisateurs", tasks_path(params.except(:user_id)), role: "menuitem", tabindex: "-1"
      - current_account.users.each do |account_user|
        %li{role: "menuitem"}
          = link_to tasks_path(params.merge(user_id: account_user.id)), role: "menuitem", tabindex: "-1" do
            .pic.pic-mini= image_tag account_user.avatar
            = account_user
  .dropdown
    %button.btn.btn-tertiary.dropdown-toggle{"data-toggle" => "dropdown", type: "button"}
      = params[:project_id].present? ? Project.find(params[:project_id]) : "Tous les projets"
      %i.entypo.caret-ed
    %ul.dropdown-menu{"aria-labelledby" => "dropdownMenu2", role: "menu"}
      - if params[:project_id]
        %li{role: "menuitem"}
          = link_to "Tous les projets", tasks_path(params.except(:project_id)), role: "menuitem", tabindex: "-1"
      - current_account.projects.each do |account_project|
        %li{role: "menuitem"}
          = link_to tasks_path(params.merge(project_id: account_project.id)), role: "menuitem", tabindex: "-1" do
            .pic.pic-mini= image_tag account_project.avatar
            = account_project
#dash-tasks.row-fluid
  .section-title
    .title
      .badge.badge-medium.badge-shy= @pending_tasks.size
      /tâches
    .title-infos
      dont
      .badge.badge-small.badge-black= @pending_tasks.overdue.size
      en retard,
      .badge.badge-small.badge-red= @pending_tasks.due_today.size
      pour aujourd’hui
= render :partial => "pending", :locals => {:tasks => @pending_tasks, :asset => nil}

app/views/tasks/new.js.erb
$('#myModalContent').replaceWith('<%= j render("ajax_form") %>');
$('.datepicker').datetimepicker();

$('.task_calendar').hide();

$('#task_bucket').change(function() {
  $('.datepicker').val("");
  if ( $(this).val() == "specific" ) {
    $('.task_calendar').css('display', 'inline-block');
    $('.datepicker').focus();
  } else {
    $('.task_calendar').hide();
  }
});

$('.datepicker').change(function() {
  $('#task_bucket').val("specific");
});

$('#myModal').modal('toggle')

app/views/tasks/uncomplete.js.erb
li_task = $('#task_<%= @task.id %>');
if (li_task.parent().is("strike")) {
	li_task.unwrap("<strike></strike>");	
}
else {
	li_task.wrap("<strike></strike>");
	setTimeout("uncomplete(li_task)",1000);
}


function uncomplete(li_task) {
	checkbox = li_task.find("input");
	if (checkbox.is(':checked') == false) {
		li_task.fadeOut(500, function() { clean_and_refresh_uncompleted_tasks(li_task)  });
	}
}

function clean_and_refresh_uncompleted_tasks(li_task) {
	li_task.remove();
  
  var $counter = $("#pending_tasks_wrapper .title-infos .badge");
  $counter.text( Number($counter.text())+1 );
  
  var $counter2 = $("#completed_tasks_wrapper .title-infos .badge");
  $counter2.text( Number($counter2.text())-1 );
  
	pending_tasks = $('#pending_tasks');
	if (pending_tasks.length > 0) {
		<% if @task.asset %>
			pending_tasks.replaceWith("<%= j render(partial:'pending', locals: {tasks: @task.asset.tasks.pending, asset: @task.asset}) %>")
		<% else %>
			pending_tasks.replaceWith("<%= j render(partial:'pending', locals: {tasks: Task.order("due_at ASC").pending, asset:nil}) %>")
		<% end %>
	}
		
}

app/views/tasks/update.js.erb
$('#myModal').modal('hide');
<% if @redirect %>
	window.location='<%= tasks_path %>'
<% else %>

	$('#myModal').replaceWith("<%= j render 'layouts/modal' %>");
	
	$('#contact_tabs a[href="#tasks"]').tab("show")
	
	pending_tasks = $('#pending_tasks');
	if (pending_tasks.length > 0) {
		counter = $("#pending_tasks_wrapper .title-infos .badge");
		counter.text( Number(counter.text())+1 );
		pending_tasks.replaceWith("<%= j render(partial:'pending', locals: {tasks: @task.asset.tasks.pending, asset: @task.asset}) %>")
	}	
	else {
		$('#empty_tasks').replaceWith("<%= j render(partial:'tasks/tasks', locals: {asset: @task.asset, pending_tasks: @pending_tasks, completed_tasks: @completed_tasks}) %>");
	}

<% end %>