config/routes.rb
Edgar::Application.routes.draw do
  get "backdoor/play1"
  get "backdoor/play2"
  get "backdoor/play3"
  get "tags/index"

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/  do
    authenticated :user do
      root :to => 'home#index'
      get "search/index"
    end

    devise_scope :user do
      root :to => "showcase#index", :as => "locale_root", constraints: {subdomain: 'www'}
      match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
      match '', to: 'sessions#new', constraints: {subdomain: /.+/}
      get "features", to: "showcase#features"
      get "about", to: "showcase#about"
    end

    devise_for :users, :controllers => { :registrations => "registrations", :confirmations => "confirmations", :sessions => "sessions"}
    match 'users/bulk_invite/:quantity' => 'users#bulk_invite', :via => :get, :as => :bulk_invite
    resources :users do
      get 'invite', :on => :member
    end

    get "welcome", to: "welcome#index"
    get "home", to: "home#index"
    get "dashboard", to: "dashboard#index"

    resources :structures do
      put 'people/:id/set_main_person', action: :set_main_person, as: :set_main_person
      resources :people
    end
    resources :people_structures, only: [:create]
    resources :festivals
    resources :show_buyers
    resources :venues do
      resources :people
      resources :tasks do
        put 'complete', :on => :member
        put 'uncomplete', :on => :member
      end
    end
    resources :people do
      resources :tasks do
        put 'complete', :on => :member
        put 'uncomplete', :on => :member
      end
    end
    resources :tasks do
      put 'complete', :on => :member
      put 'uncomplete', :on => :member
    end
    resources :contacts do
      get 'autocomplete', on: :collection
      put 'bulk', on: :collection
      resources :tasks do
        put 'complete', :on => :member
        put 'uncomplete', :on => :member
      end

      get 'only/:filter', action: :only, on: :collection, as: :only
      get 'add_to_favorites', on: :member
      get 'remove_to_favorites', on: :member
      get 'show_map', on: :collection
    end

    resource :account do
      put 'import_samples', action: :import_samples, as: :import_samples
      delete 'destroy_test_contacts', action: :destroy_test_contacts

      resources :abilitations
    end

    resources :reportings

    resources :campaigns
    resources :opportunities

    resources :projects

    resources :styles, only: [:index]
    resources :networks, only: [:index]
    resources :customs, only: [:index]

    resources :jobs, only: [:show]

    resources :contacts_imports, only: [:new, :create, :update]
    get 'contacts_imports/new_with_details', to: 'contacts_imports#new_with_details', as: :new_with_details_contacts_import

    resources :contacts_exports, only: [:new]

    resources :announcements, only: [:index]
    resources :coupons, only: [:index, :new, :create, :update]
    resources :addresses, only: [:update]
    resource :subscription, only: [:new, :edit, :create, :update]
  end

  require "sidekiq/web"
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end if Rails.env.production?
  mount Sidekiq::Web, at: "/sidekiq"

  root to: redirect("/#{I18n.default_locale}")
end

app/models/show_buyer.rb
class ShowBuyer < ActiveRecord::Base
  include Organizer

  default_scope { where(:account_id => Account.current_id) }

  attr_accessible :licence, :structure_attributes, :schedulings_attributes, :avatar, :remote_avatar_url
  has_one :structure, as: :structurable, dependent: :destroy
  accepts_nested_attributes_for :structure

  has_many :schedulings, dependent: :destroy, order: "id ASC"
  accepts_nested_attributes_for :schedulings, :reject_if => :all_blank, :allow_destroy => true

  has_many :show_hosts, through: :schedulings, uniq: true

  delegate :name, :contact, to: :structure

  mount_uploader :avatar, AvatarUploader

  delegate :name, :people, :tasks, :reportings, :remark, :addresses, :emails, :phones, :websites, :city, :address, :network_list, :custom_list, :contacted?, :favorite?, :main_person, to: :structure

  before_save :set_contact_criteria

  scope :by_contract, lambda { |tag_name| joins(:schedulings).where("schedulings.contract_tags LIKE ?", "%#{tag_name}%") }
  scope :by_style, lambda { |tag_name| joins(:schedulings).where("schedulings.style_tags LIKE ?", "%#{tag_name}%") }

  def fine_model
    self
  end

  def set_contact_criteria
    self.build_structure unless structure.present?
    self.structure.build_contact unless structure.contact.present?
    contact = structure.contact

    c_style_list = self.style_list
    contact.style_tags = c_style_list.join(',') if c_style_list.present?

    c_contract_list = self.contract_list
    contact.contract_tags = c_contract_list.join(',') if c_contract_list.present?

  end

  def contract_list
    cl = []
    self.schedulings.each do |s|
      s.contract_list.each do |c|
        cl.push(c) unless cl.include?(c)
      end
    end
    cl
  end

  def style_list
    Scheduling.style_for(self)
  end

  def self.from_csv(row)
    show_buyer = ShowBuyer.new
    show_buyer.licence = row.delete("licence".to_sym)
    scheduling = Scheduling.from_csv(row)
    show_buyer.schedulings << scheduling if scheduling
    show_buyer.structure, invalid_keys = Structure.from_csv(row)
    [show_buyer, invalid_keys]
  end

end

app/controllers/show_buyers_controller.rb
class ShowBuyersController < ApplicationController
  include ApplicationHelper

  def index
    if params[:kind]
      @filtered_by = "(#{params[:kind]})"
      @contacts = ShowBuyer.joins(:structure => :contact).order(:name).by_type(params[:kind]).page params[:page]
    else
      @contacts = ShowBuyer.page params[:page]
    end
    respond_to do |format|
      format.html { render "contacts/index"}
      format.json { render json: @contacts }
    end
  end

  def show
    @show_buyer = ShowBuyer.find(params[:id])
    add_asset(@show_buyer.structure.contact)
    @structure = @show_buyer.structure
    @main_person = @show_buyer.main_person(current_user)
    @people = @show_buyer.structure.people
    @tasks = @show_buyer.structure.tasks
    @pending_tasks = @tasks.pending
    @completed_tasks = @tasks.completed
    @reportings = @show_buyer.structure.reportings
    @reporting = @show_buyer.structure.reportings.build
  end

  def new
    session[:return_to] = request.referer
    @show_buyer = ShowBuyer.new
    @show_buyer.build_structure
    @show_buyer.structure.build_contact
    @show_buyer.addresses.build

    respond_to do |format|
      format.html
      format.json { render json: @venue }
    end
  end

  def edit
    @show_buyer = ShowBuyer.find(params[:id])
    add_asset(@show_buyer.structure.contact)
    @show_buyer.schedulings.build(name: "Programmation") unless @show_buyer.schedulings.any?
  end

  def update
    @show_buyer = ShowBuyer.find(params[:id])
    respond_to do |format|
      if @show_buyer.update_attributes(params[:show_buyer])
        format.html do
          session.delete(:return_to)
          redirect_to @show_buyer, notice: t("activerecord.notices.models.show_buyer.updated", name: @show_buyer.name)
        end
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @show_buyer.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @show_buyer_id = params[:id]
    @show_buyer = ShowBuyer.find(@show_buyer_id)
    @show_buyer.destroy

    respond_to do |format|
      format.html { redirect_to show_buyers_url }
      format.js { render "destroy" }
    end
  end

end

app/views/show_buyers/_form.html.haml
- content_for :scripts do
  = javascript_include_tag "contacts"
  = javascript_include_tag "tag"
  = javascript_include_tag "contacts_form"

#menu-vertical
  %span
    = link_to t(:cancel), @show_buyer
    ou
  .btn.btn-alert.btn-large.btn-submit{:href => "#"}
    Enregistrer
  

%h1.page-title Modifier l'organisateur de spectacles
/%h2= @show_buyer.name

= simple_nested_form_for(@show_buyer, :html => { :class => 'form-horizontal form-edit' }) do |f|
  /simple_form_for(@article, :html => { :class => 'form-horizontal' }) do |f|
  = display_errors(@show_buyer)
  
  .form-inputs
    %header
      .control-group
        .pic-container
          .pic= image_tag @show_buyer.avatar_url
        = f.fields_for :structure do |s|
          = s.fields_for :contact do |c|
            = c.input :name, label: false, :class => "input-Xlarge"
        = f.input :avatar, label:false, :hint => "L’image doit faire au moins 80x80 pixels."
  
    .row-fluid
      .span12
        .tabbable
          / ________________________________________________________ nav-tabs _________________
          %ul.nav.nav-tabs
            %li.active
              %a{"data-toggle" => "tab", :href => "#contact-infos"} Coordonnées
            %li
              %a{"data-toggle" => "tab", :href => "#basic-infos"} Infos
            %li
              %a{"data-toggle" => "tab", :href => "#schedulings"} Programmation(s)
          
          
          .tab-content
            / ________________________________________________________________________________________________________________ contact-infos
            #contact-infos.tab-pane.active
              /.section-title
              /.title Coordonnées
              / ________________________________________________________ email
              = f.fields_for :structure do |s|
                = s.fields_for :contact do |c|

                  = c.fields_for :emails do |email|
                    .nested-fields
                      = email.link_to_remove :title => "Remove this email" do
                        %i.entypo.edi-minus2
                      = email.input :address, label:"Email", :wrapper => :append do
                        = email.input_field :address, :label => "Email", :validate => true, :class => "input-xlarge"
                        = email.input_field :classic_kind, :label => "Type", :collection => Email::VENUE_KIND, :class => "add-on btn dropdown-toggle"
                        = email.input_field :specific_kind, :class => "other input-medium"
                  .links
                    = c.link_to_add :emails, :title => 'Add a new email' do
                      %i.entypo.edi-plus2
                      Add a new email


                  / ________________________________________________________ phone
                  = c.fields_for :phones do |phone|
                    .nested-fields
                      = phone.link_to_remove :title => "Remove this phone" do
                        %i.entypo.edi-minus2
                      = phone.input :national_number, :wrapper => :append do
                        = phone.input_field :national_number, :class => "input-medium", :validate => true
                        = phone.input_field :classic_kind, label:false, :collection => Phone::VENUE_KIND, :class => "add-on btn dropdown-toggle"
                        = phone.input_field :specific_kind, :class => "other input-medium"
                  .links
                    = c.link_to_add :phones, :title => 'Ajouter un téléphone' do
                      %i.entypo.edi-plus2
                      Add a new phone



                  / ________________________________________________________ address
                  .fields-group
                    = c.fields_for :addresses do |address|
                      .nested-fields.addresses
                        = address.link_to_remove :title => "Remove this address" do
                          %i.entypo.edi-minus2

                        = address.input :street, label:"Addresse", :wrapper => :append do
                          = address.input_field :street,:placeholder =>"Addresse",  :label => false, :input_html => { :class => "input-xlarge" }
                          = address.input_field :kind, :label => false, :collection => [:main_address, :admin_address], :selected => "Work", :input_html => { :class => "add-on btn dropdown-toggle" }
                          
                          
                        .control-group.nolabel
                          = address.input_field :city, :label => false, :placeholder =>"Ville, localité, …", :class => " inline"
                          = address.input_field :postal_code, :label => false, :placeholder =>"Code postal", :class => "input-medium inline"
                          = address.input_field :country, :label => false, :priority => [ "France", "Spain", "Germany", "Austria", "United States", "United Kingdom" ], :class => "inline"
                        .control-group.nolabel.state.hidden
                          = address.input_field :state, :label => false, :placeholder =>"State", :class => "inline"
                      
                        = address.input :more_info, label:false

                    .links
                      = c.link_to_add :addresses, :title => 'Add a new address' do
                        %i.entypo.edi-plus2
                        Add a new address



                  / ________________________________________________________ website
                  = c.fields_for :websites do |website|
                    .nested-fields
                      = website.link_to_remove :title => "Remove this website" do
                        %i.entypo.edi-minus2
                      /= website.input :url, :label => "Website"
                      /= website.input :kind, :label => "Type", :collection => %w(Work Home),  :selected => "Work"

                      /= website.input :url, wrapper: :with_tooltip, tooltip: "Coucou tooltip" do
                      = website.input :url, wrapper: :append do
                        = website.input_field :url, :class => "input-xlarge"
                        = website.input_field :kind, label:false, :collection => %w(Work Home),  :selected => "Work", :class => "add-on btn dropdown-toggle"

                  .links
                    = c.link_to_add :websites, :title => 'Add a new website' do
                      %i.entypo.edi-plus2
                      Add a new website

            / ________________________________________________________________________________________________________________ contact-infos
            #basic-infos.tab-pane
              /%section#basic-infos
              /.section-title
              /.title Infos lieu
    


              = f.fields_for :structure do |s|
                = s.fields_for :contact do |c|

                  -#  ________________________________________________________ TAGS V1
    
                  = c.input :network_tags, label: "Réseaux <br><span class='help-block'>(séparés par des virgules)</span>".html_safe, :input_html => { :class => "span12 network_tags_input", :placeholder =>"…", data: {autocomplete_source: networks_path} }

                  -#  ________________________________________________________ TAGS V1
                  = c.input :custom_tags, label: "Tags personnalisés<br><span class='help-block'>(séparés par des virgules)</span>".html_safe, :input_html => { :class => "span12 custom_tags_input", :placeholder =>"…", data: {autocomplete_source: customs_path} }
    




                  -# ________________________________________________________ Observations
                  = f.fields_for :structure do |s|
                    = s.fields_for :contact do |c|
                      = c.input :remark



                    
            -#  ________________________________________________________ contracts

            / ________________________________________________________________________________________________________________ contact-infos
            #schedulings.tab-pane

              = f.fields_for :schedulings do |v|
                -#, :class => "span4"
                -#, :input_html => { :class => "span4" }
                .nested-fields
                  = v.link_to_remove :title => "Supprimer cette programmation" do
                    %i.entypo.edi-minus2
                  = v.input :name
                  
                  -# = v.input :external_show_host, collection: ["Lieu ou Festival", "Lieu éphémère"], as: :radio_buttons, item_wrapper_class: "inline"  
                  = v.hidden_field :show_host_kind, value:"Venue"
                  
                  = v.input :show_host_name, input_html: {autocomplete:"off", class: "jq_autocomplete", data: {autocomplete_source: structures_path(type: "ShowHost")} }
                  
                  
                  = v.input :scheduler_name, input_html: {autocomplete:"off", class: "jq_autocomplete", data: {autocomplete_source: people_path} }
                  -# = v.input :scheduler, input_html: {autocomplete:"off", class: "jq_autocomplete", data: {autocomplete_source: people_path} }
                  = v.input :contract_list, :collection => Scheduling::CONTRACT_LIST, :as => :check_boxes, item_wrapper_class:"inline"
          

                  = v.input :style_tags, label: "Styles programmés<br><span class='help-block'>(séparés par des virgules)</span>", :input_html => { :class => "span6 style_tags_input", :placeholder =>"Rock, humour…", data: {autocomplete_source: styles_path} }


                  %label.control-label Type d'artistes
                  = v.input :discovery, wrapper: :edgar_checkbox
          
      
                  -#  ________________________________________________________ period
                  = v.input :period, :collection => [:all_year, :quaterly, :per_semester], as: :radio_buttons, item_wrapper_class: "inline"

              
              
                  .control-group  
                    %label.control-label #{t("simple_form.labels.schedulings.prospecting")}
                    .controls.swipeable
                      -#= f.input_field :season_months, collection: ["Jan","Fev", "Mar","Avr","Mai","Juin","Juil","Aout","Nov","Dec"], as: :check_boxes
                      = v.input_field :prospecting_months, collection: (1..12).to_a, label_method: lambda {|index| t("date.abbr_month_names")[index.to_i]}, as: :check_boxes
                  
                  = v.input :remark

              .links
                = f.link_to_add :schedulings, :title => 'Ajouter une programmation' do
                  %i.entypo.edi-plus2
                  Ajouter une programmation

                                  
    
    
    
              

                

    / ________________________________________________________ actions
    .form-actions
      = f.button :submit, :class => "btn-primary btn-large btn-alert"
      ou
      = link_to t(:cancel), @show_buyer

app/views/show_buyers/_infos.html.haml
- content_for :infos do
  / _____________________________________________ right    
  %ul.list-infos
    /%i.entypo.edi-info
    = render @show_buyer.schedulings
  
= render partial: "structures/info", locals: {structure: @structure}  

app/views/show_buyers/_show_buyer.html.haml
%li{id: "show_buyer_#{show_buyer.to_param}"}
  = render partial: "contacts/contact_elem", locals: {contact: show_buyer.structure.contact, edit_link_path:edit_show_buyer_path(show_buyer) }
  

  .mainrow
    = link_to show_buyer do
      %h3
        = show_buyer.name
        - if show_buyer.contact.making_prospecting?
          %a.badge.badge-green.badge-capsule En recherche active
        - if show_buyer.contact.has_duplicates?
          = link_to "Doublon", contacts_path(duplicate_of: show_buyer.contact.dup_id), class: "a badge badge-grey doublons"

      .pic= image_tag show_buyer.avatar_url
    .infos-line
      / = render venue.capacities if venue.capacities
      = render show_buyer.address if show_buyer.address
      
    .tags
      = render partial: "tags/tags", locals: { contact: show_buyer.structure.contact}

app/views/show_buyers/destroy.js.erb
$("#show_buyer_<%= @show_buyer_id %>").fadeOut(function() {$(this).remove(); })

app/views/show_buyers/edit.html.haml
/%h1 Editing venue

= render 'form'

app/views/show_buyers/show.html.haml
-# _____________________________________  SHOW VENUE

-#-content_for :extra_navtabs do
  %li
    %a{"data-toggle" => "tab", :href => "#dates"} Dates
    

-#-content_for :extra_content_tabs do
  / ________________________________________________________ dates              
  #dates.tab-pane
    /%p Dates de spectacle
    %ul.list-large
      %li
        .meta
          .badge.badge-red En attente de payement
        .actions
          /= link_to 'Edit', edit_venue_path(venue)
          %a.shybtn{:href => "#"}
            %i.entypo.edi-pencil
            
        %h4
          %a{:href => "#"}
            .pic= image_tag "squared/pro4.jpg"
            Lundi 1 juin 2013 — NomDuProjet
          
        .infos-line
          /%span NomDuProjet
          %span Formule
          —
          %span Responsable :
          .pic.pic-mini= image_tag "squared/per3.jpg"
          %a{:href => "#"} Christophe R.
          
      %li
        .meta
          .badge.badge-green Validé
        .actions
          /= link_to 'Edit', edit_venue_path(venue)
          %a.shybtn{:href => "#"}
            %i.entypo.edi-pencil
            
        %h4
          %a{:href => "#"}
            .pic= image_tag "squared/pro3.jpg"
            Samedi 5 Juillet 2013 — AutreProjet
          
        .infos-line
          /%span NomDuProjet
          %span Formule
          —
          %span Responsable :
          .pic.pic-mini.pic-user= image_tag "squared/per2.jpg"
          %a{:href => "#"} Christophe R.
          
          
      %li
        .meta
          .badge.badge-blue Option
        .actions
          /= link_to 'Edit', edit_venue_path(venue)
          %a.shybtn{:href => "#"}
            %i.entypo.edi-pencil
            
        %h4
          %a{:href => "#"}
            .pic= image_tag "squared/pro2.jpg"
            Lundi 1 juin 2013 — NomDuProjet
        .infos-line
          /%span NomDuProjet
          %span Formule
          —
          %span Responsable :
          .pic.pic-mini.pic-user= image_tag "squared/per2.jpg"
          %a{:href => "#"} Christophe R.


= render partial: "structures/show", locals: {structure: @show_buyer.structure, edit_link_path: edit_show_buyer_path(@show_buyer)}